### PR TITLE
Improve android performance

### PR DESCRIPTION
**Pull request by veloce**
Since NEON is not supported in armv7 devices I used an abi filter to keep only armv8.

So it's up to you if you want to merge this. Note that afaik performance of NNUE evaluation is really degraded without NEON support, so older devices should use classical evaluation instead.

To solve this problem in current lichess application, I use 2 engines: one compiled with NNUE and NEON for armv8 and one compiled without for armv7.

The best solution, perhaps, would be to compile it for both architectures using different flags for each one, but I don't know how to do that.

### CODE REVIEW

**Comment by daohoangson** [comment]
I think this should work:

- Reverted the changes in `build.gradle` because we want to support the widest range of devices out there. I couldn't find any API 16 to test though... Still working on our integration test suite at #21
- Added an arch check before turning on `USE_NEON` complier option. Again, I don't have any armv7 device to verify the build.

Apparently most armv7 devices do have NEON support but the lib has to do runtime check before executing the fast code path so we are only enable armv8 for now. In my testing, the NEON build is about 35% faster.

| Without NEON | USE_NEON |
| --- | --- |
| without | neon |


```diff
diff --git a/android/CMakeLists.txt b/android/CMakeLists.txt
index 7d9be50..a87a572 100644
--- a/android/CMakeLists.txt
+++ b/android/CMakeLists.txt
@@ -7,6 +7,9 @@ add_library(
   ../ios/FlutterStockfish/ffi.cpp
   ${cppPaths}
 )
-target_compile_options(stockfish PRIVATE -std=c++17 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_POPCNT -DUSE_NEON)
+
+if(ANDROID_ABI STREQUAL arm64-v8a)
+  target_compile_options(stockfish PRIVATE -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_POPCNT -DUSE_NEON)
+endif()
 
 file(DOWNLOAD https://tests.stockfishchess.org/api/nn/nn-6877cd24400e.nnue ${CMAKE_BINARY_DIR}/nn-6877cd24400e.nnue)
diff --git a/android/build.gradle b/android/build.gradle
index e898eb3..34d1941 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -25,11 +25,10 @@ android {
     compileSdkVersion 29
 
     defaultConfig {
-        minSdkVersion 21
+        minSdkVersion 16
         externalNativeBuild {
             cmake {
-                arguments '-DANDROID_ARM_NEON=TRUE'
-                abiFilters 'arm64-v8a'
+                cppFlags "-std=c++17"
             }
         }
     }
```

**Comment by veloce** [comment]
I think it's good like, having the widest range of supported devices is the way to go. Can you push your changes directly to this branch?

I'd even do:
```
if(ANDROID_ABI STREQUAL arm64-v8a)
  target_compile_options(stockfish PRIVATE -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT - DUSE_POPCNT -DUSE_NEON)
else
  target_compile_options(stockfish PRIVATE -DUSE_PTHREADS -DNDEBUG -O3)
endif()
```

as it should improve the speed a bit for older devices too. 

I don't have any armv7 device but I assume it is safe to compile with NEON only for armv8. We'll open soon external testing for the new lichess mobile app, that is a way to find armv7 testers perhaps.

**Comment by daohoangson** [comment]
No, I couldn't push to the `lichess-org` fork. I also changed your patch a bit:

```
if(ANDROID_ABI STREQUAL arm64-v8a)
  target_compile_options(stockfish PRIVATE -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_POPCNT -DUSE_NEON)
else()
  target_compile_options(stockfish PRIVATE -DUSE_PTHREADS -DNDEBUG -O3)
endif()
```

Checked building for `armv8`, `armv7` and `x86_64`.

**Comment by veloce** [comment]
I don't mind if you close this PR and opens a new one with your changes then.

**Comment by daohoangson** [comment]
Hmm, OK. Let's me try that.

**Comment by daohoangson** [comment]
Can you take a look at #21? I'm trying to setup Android pipeline before making this change.

**Comment by daohoangson** [comment]
Closing in favor of #26.

**Pull request closed without merging**
